### PR TITLE
Enable switching between baseline and alternative geometries

### PR DESCRIPTION
**Pull request by drbenmorgan**
This updates `WLGDDetectorConstruction` to enable switching between the two geometries via a new UI command `WLGD/detector/setGeometry baseline|alternative`. The argument is made a string to enable future extension if required. The command calls a new member function that calls the appropriate kernel function to reset/init the geometry.

A basic test has been added to exercise this, and seems to pass, but there are warning messages from each worker thread when running after any geometry swap:

```
G4WT0 > 
2: -------- WWWW ------- G4Exception-START -------- WWWW -------
2: *** G4Exception : DET1010
2:       issued by : G4SDStructure::AddNewDetector()
2: Det had already been stored in /. Object pointer is overwitten.
2: It's users' responsibility to delete the old sensitive detector object.
2: *** This is just a warning message. ***
2: -------- WWWW -------- G4Exception-END --------- WWWW -------
...
2: G4WT0 > 
2: -------- WWWW ------- G4Exception-START -------- WWWW -------
2: *** G4Exception : BIAS.MNG.01
2:       issued by : G4VBiasingOperator::AttachTo(...)
2: Biasing operator `TestManyExponentialTransform' can not be attached to Logical volume `Water_log' which is already used by an other operator !
2: 
2: *** This is just a warning message. ***
2: -------- WWWW -------- G4Exception-END --------- WWWW -------
```

Still trying to track these down, so review/comments needed.

### CODE REVIEW

**Comment by yramachers** [comment]
Not surprisingly, I get the same. First the master complains and then each worker thread sends the same warnings again. The code finishes gracefully but I am not sure whether the biasing is actually switched on. Trajectories are stored though.
When I got similar messages, I looked up how to delete (developer responsibility) a sensitive detector and couldn't find a method. All I could think of was wrapping the setsensitive method in a clause to check whether there is already one but that was clearly not correct since that previously registered pointed at a destroyed geometry etc. It should be removed and newly declared, I think. Same for the bias attachment to logical volumes. Those are also destroyed and re-built. What ever I did however went wrong at which point I gave up.

**Comment by drbenmorgan** [comment]
O.k., I'll dig into that a bit more - the SD should be pretty standard, not sure about the biasing though. It's not clear to me yet who owns the biasing objects.

**Comment by drbenmorgan** [comment]
@yramachers, I _think_ I've fixed the warnings now. These were tracked to needing to clear the geometry stores before (re)constructing the geometry after a change, plus managing the SD via a `G4Cache` wrapper. 

Whilst `ReinitializeGeometry` has an argument to automatically clear the stores, it can't (seemingly) be called by the `SetGeometry` member function without inducing a segfault. Looking at the examples that use this, the needed manual clearing of the stores is still used.

The SD is a bit odd - basically, the SD is thread-local, but the geometry is global. So the SD itself is stored wrapped in a `G4Cache` object, and only added to the manager once.

I still want to resolve the ownership of the biasing objects created in `CreateSDandField`.

With the warnings resolved, could you check things and see if the outputs are still as you would expect please?

**Comment by drbenmorgan** [comment]
I'm also not sure what the CI is now failing as nothing has changed here since yesterday (and things compile fine). Possibly a CVMFS issue hence the additional commit to check the environment.

**Comment by drbenmorgan** [comment]
Thanks! CI seems borked due to some CVMFS issue. I'll merge at end of today if I'm unable to resolve that. Will place a note to check on biasing object ownership.

**Pull request merged**
