### PR TITLE
Hall A

### PR DESCRIPTION
**Pull request by yramachers**
Following the email, showing the code is of course the better option, see this PR. Something is not as it should be in this new geometry hence this PR needs changes before merging.

### CODE REVIEW

**Comment by drbenmorgan** [comment]
Thanks @yramachers, will take a look!

**Comment by yramachers** [comment]
Thanks for the copy number hint in the manual @drbenmorgan . I think that could be the solution, see our PrimitiveScorers. Something might be going wrong with the 'key' in the map. All the scorers have a consecutive counter as key. However, all the PScorer examples take the GetIndex() as key which I don't understand hence the change to a counter. With the copy numbers having to derive even from mother volumes, there must be more to it than I understand.
That could be a way forward and easy to change, i.e. all our PScorers are simple.

**Comment by yramachers** [comment]
Ah, and I ignored the primitive scorer 'depth' argument which results in the correct index value, i.e. copy number of mother volume, as in line 74 in 
https://gitlab.cern.ch/geant4/geant4/-/blob/master/source/digits_hits/detector/src/G4VPrimitiveScorer.cc

**Comment by drbenmorgan** [comment]
@yramachers, is this now ready for merge, assuming tests pass?

**Comment by yramachers** [comment]
Not quite, sorry. I still have neutrons in the particle filter since I need scores to come in reasonable time. I then check the output, see whether I can image all detectors with neutron hits. Worked fine with zero energy hits but since that is a bit dodgy, I now ramped up the bias and see proper hits. I think the geometry for hall A is now fine and all detector volumes are scoring but still want to see it with the hit coordinates in the output. After that, I take neutrons out again and we should be scoring proper Ge-77 production.

**Comment by yramachers** [comment]
@drbenmorgan It should be fine to merge this branch. The big ticket item is less the hall A implementation but the bug I found in the Ge density. No idea how that happened. I remember the correct value but somehow must have typed not only the wrong value but worse, the wrong unit! It stood at mg/cm3 instead of g/cm3. That would of course explain a strongly diminished reaction rate. Since that was in the material definition function, it fed through to all geometry implementations. I am testing hall A no my workstation but at the slightest sign of increased reaction rates, I'll have to re-run all batch jobs which is a good thing since I didn't believe the previous results.

**Comment by drbenmorgan** [comment]
Thanks @yramachers, good point to merge with the bug fix!

**Review by drbenmorgan — APPROVED** [review]

**Pull request merged**
